export const TOP_SCORER_OPTIONS = [
  { id: 'mbappe', name: 'Kylian Mbappé', team: 'France', flag: '🇫🇷', rank: 3 },
  { id: 'kane', name: 'Harry Kane', team: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', rank: 4 },
  { id: 'yamal', name: 'Lamine Yamal', team: 'Spain', flag: '🇪🇸', rank: 2 },
  { id: 'vinicius', name: 'Vinícius Jr.', team: 'Brazil', flag: '🇧🇷', rank: 6 },
  { id: 'alvarez', name: 'Julián Álvarez', team: 'Argentina', flag: '🇦🇷', rank: 1 },
  { id: 'havertz', name: 'Kai Havertz', team: 'Germany', flag: '🇩🇪', rank: 9 },
  { id: 'ronaldo', name: 'Cristiano Ronaldo', team: 'Portugal', flag: '🇵🇹', rank: 5 },
  { id: 'gakpo', name: 'Cody Gakpo', team: 'Netherlands', flag: '🇳🇱', rank: 8 },
  { id: 'haaland', name: 'Erling Haaland', team: 'Norway', flag: '🇳🇴', rank: 20 },
  { id: 'diaz', name: 'Luis Díaz', team: 'Colombia', flag: '🇨🇴', rank: 15 },
  { id: 'lukaku', name: 'Romelu Lukaku', team: 'Belgium', flag: '🇧🇪', rank: 7 },
  { id: 'nunez', name: 'Darwin Núñez', team: 'Uruguay', flag: '🇺🇾', rank: 10 },
  { id: 'gimenez', name: 'Santiago Giménez', team: 'Mexico', flag: '🇲🇽', rank: 16 },
  { id: 'pulisic', name: 'Christian Pulisic', team: 'USA', flag: '🇺🇸', rank: 17 },
  { id: 'ueda', name: 'Ayase Ueda', team: 'Japan', flag: '🇯🇵', rank: 13 },
  { id: 'ziyech', name: 'Hakim Ziyech', team: 'Morocco', flag: '🇲🇦', rank: 25 },
  { id: 'son', name: 'Son Heung-min', team: 'South Korea', flag: '🇰🇷', rank: 19 },
  { id: 'kramaric', name: 'Andrej Kramarić', team: 'Croatia', flag: '🇭🇷', rank: 11 },
  { id: 'embolo', name: 'Breel Embolo', team: 'Switzerland', flag: '🇨🇭', rank: 12 },
  { id: 'david', name: 'Jonathan David', team: 'Canada', flag: '🇨🇦', rank: 30 },
  { id: 'salah', name: 'Mohamed Salah', team: 'Egypt', flag: '🇪🇬', rank: 29 },
  { id: 'valencia', name: 'Enner Valencia', team: 'Ecuador', flag: '🇪🇨', rank: 27 },
  { id: 'guler', name: 'Arda Güler', team: 'Türkiye', flag: '🇹🇷', rank: 14 },
  { id: 'sabitzer', name: 'Marcel Sabitzer', team: 'Austria', flag: '🇦🇹', rank: 34 },
];

export const ALL_WC_TEAMS = [
  'Argentina', 'Spain', 'France', 'England', 'Portugal', 'Brazil', 'Belgium',
  'Netherlands', 'Germany', 'Uruguay', 'Croatia', 'Switzerland', 'Japan',
  'Türkiye', 'Colombia', 'Mexico', 'USA', 'Sweden', 'South Korea', 'Norway',
  'Czechia', 'Paraguay', 'Saudi Arabia', 'Bosnia and Herzegovina', 'Morocco',
  'Iran', 'Ecuador', 'Senegal', 'Egypt', 'Canada', 'Algeria', 'Ivory Coast',
  'Scotland', 'Austria', 'Australia', 'Ghana', 'South Africa', 'Uzbekistan',
  'Tunisia', 'Cabo Verde', 'DR Congo', 'Panama', 'Qatar', 'Haiti', 'Iraq',
  'Curaçao', 'New Zealand', 'Jordan',
];
